---
- hosts: dev
  gather_facts: no
  become: True
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Update apt packages
      apt:
        update_cache: "yes" 
        force_apt_get: "yes"

    - name: get the facts for default pip, pip2 and pip3.6
      pip_package_info:
        clients: ['python-docker', 'docker-py', 'pip3.6']
    
#    - name: Install docker-py python module
#      pip:
#        name: python-docker
#        state: present
#    - name: Install docker-py python module
#      pip:
#       name: docker-py
#        state: present    
    - name: Start the container
      docker_container:
        name: ci-cd-app
        image: "heyymonth/testimage:${DOCKER_TAG}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
