---
- hosts: dev
  gather_facts: no
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: ci-cd-app
        image: "heyymonth/testimage:${DOCKER_TAG}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
